name: Build rpi-alpine image

on:
  workflow_dispatch:
  
    inputs:
         arch:
          type: choice
          required: true
          description: RPI Architecture
          options: 
          - armhf
          - aarch64
         version:
           description: 'Version Release'
           required: true
           default: 'v1.6.0'
         detail:
           description: 'Extra Notes'
           required: false
           default: 'Excelsior!'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: |
        docker build runner -t runner
        docker run --privileged --rm -v /dev:/dev:ro -v "$PWD":/runner -w /runner -e ALPINE_BRANCH=edge -e ALPINE_MIRROR="http://dl-cdn.alpinelinux.org/alpine" -e ARCH=${{ github.event.inputs.arch }} runner ./make-image

    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sudo snap install hub --classic
        build_date=$(date +%Y%m%d)
        build_number=$[$(git tag | grep $build_date | wc -l) + 1]
        tag="$build_date.$build_number"
        hub release create $tag -m "$tag" -a dist/*.gz
